delivery:
  confirm: Confirmar
  reject: Rechazar
  confirmed: Confirmado
  rejected: Rechazado
  confirmed_message: 'Gracias por confirmar tu entrega'
  rejected_message: 'Gracias por rechazar tu entrega. En otra oportunidad. Bendiciones.'
