username_validation: null
_core:
  default_config_hash: AIovxDkp_lDsW1hiPN3QCjOsne6vwcPRntsSYiV2tMo
langcode: es
blacklist_char: '!,@,#,$,%,^,&,*, ,(,),a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,t,u,v,w,x,y,z'
min_char: '7'
max_char: '8'
ajax_validation: 1
user_label: ''
user_desc: ''
